/* -----------------------------------------------------------------------------
System  : EZLL
Module  : BAYPLAN
Name    : V_TOS_ONBOARD_CONTAINER.sql
Purpose : V_TOS_LL_CONTAINER joined with V_TOS_DL_CONTAINER by bookings# and equipment key
--------------------------------------------------------------------------------
History : None
--------------------------------------------------------------------------------
Author		Date		    What
---------------	---------------	------------------------------------------------
Dhruv 	        06/07/2011	<Initial version>
Dhruv           07/07/2011      v0.20
Dhruv           12/07/2011      v0.30
Dhruv           13/07/2011      v0.31
Dhruv           16/09/2011      v0.32
Dhruv           22/09/2011      v0.33
Dhruv           09/11/2011      v0.34
--Change Log--------------------------------------------------------------------
##   DD/MM/YY     User-Task/CR No   -Short Description-
01   12/07/11     Dhruv             Normal view changed to Materialized view.
02   13/07/11     Dhruv             LL_LOADING_STATUS and DL_DISCHARGE_STATUS is added.
03   26/08/11     Dhruv             Added IS NULL condition, to fetch NULL values also.
04   16/09/11     Dhruv             Replaced AND with OR to fetch NULL values also. 
05   22/09/11     Dhruv             PARALLEL Hints added for query optimization.
06   09/11/11     Dhruv             DL_MLO_DEL & LL_MLO_DEL added
07   09/11/11     Dhruv             DL_MLO_POD1 & LL_MLO_POD1 added
--------------------------------------------------------------------------------
**/

DROP VIEW V_TOS_ONBOARD_CONTAINER; --##01

CREATE MATERIALIZED VIEW "V_TOS_ONBOARD_CONTAINER" --##01
("DL_SERVICE",
"DL_VESSEL",
"DL_VOYAGE",
"DL_DIRECTION",
"DL_PORT_SEQ",
"DL_FK_BOOKING_NO",
"DL_DN_EQUIPMENT_NO",
"LL_POL",
"DL_POD",
"DL_ETA",
"LL_ETD",
"DL_DN_SHIPMENT_TYP",
"DL_DN_SOC_COC",
"DL_DN_FINAL_POD",
"DL_DN_NXT_POD1",
"DL_DN_NXT_POD2",
"DL_DN_NXT_POD3",
"DL_LOAD_CONDITION",
"DL_CONTAINER_GROSS_WEIGHT",
"DL_OVERLENGTH_FRONT_CM",
"DL_OVERLENGTH_REAR_CM",
"DL_OVERWIDTH_RIGHT_CM",
"DL_OVERWIDTH_LEFT_CM",
"DL_OVERHEIGHT_CM",
"DL_REEFER_TEMPERATURE",
"DL_REEFER_TMP_UNIT",
"DL_DN_HUMIDITY",
"DL_DN_VENTILATION",
"DL_FLASH_POINT",
"DL_FLASH_UNIT",
"DL_FK_IMDG",
"DL_FK_UNNO",
"DL_STOWAGE_POSITION",
"LL_STOWAGE_POSITION",
"DL_FK_HANDLING_INSTRUCTION_1",
"DL_FK_HANDLING_INSTRUCTION_2",
"DL_FK_HANDLING_INSTRUCTION_3",
"DL_CONTAINER_LOADING_REM_1",
"DL_CONTAINER_LOADING_REM_2",
"DL_RESIDUE_ONLY_FLAG",
"DL_DN_EQ_SIZE",
"DL_DN_EQ_TYPE",
"DL_FK_PORT_CLASS",
"LL_ACTIVITY_DATE_TIME",
"DL_ACTIVITY_DATE_TIME",
"LL_RECORD_STATUS",
"LL_LL_RECORD_STATUS",
"DL_RECORD_STATUS",
"DL_DL_RECORD_STATUS",
"LL_FK_LOAD_LIST_ID",
"DL_FK_DISCHARGE_LIST_ID",
"LL_LOAD_LIST_STATUS",
"DL_DISCHARGE_LIST_STATUS",
"LL_VESSEL",
"DL_DN_TERMINAL",
"LL_DN_TERMINAL",
"DL_POD_TERMINAL",
"DL_DN_POL_TERMINAL",
"LL_DN_DISCHARGE_TERMINAL",
"DL_CONTAINER_SEQ_NO",
"LL_CONTAINER_SEQ_NO",
"DL_FK_SLOT_OPERATOR",
"DL_FK_CONTAINER_OPERATOR",
"LL_FK_SLOT_OPERATOR",
"LL_FK_CONTAINER_OPERATOR",
"LL_LOADING_STATUS",   --##02
"DL_DISCHARGE_STATUS", --##02
"DL_OUT_SLOT_OPERATOR",             --bayplan changes 18,august,2011
"DL_FK_BKG_VOYAGE_ROUTING_DTL",     --bayplan changes 18,august,2011
"DL_FINAL_DEST",                    --bayplan changes 18,august,2011
"LL_DN_DISCHARGE_PORT",             --bayplan changes 18,august,2011
"LL_DN_FULL_MT",                     --bayplan changes 18,august,2011
"LL_MLO_DEL",
"DL_MLO_DEL",
"LL_MLO_POD1",
"DL_MLO_POD1")                                 
REFRESH COMPLETE ON DEMAND 
USING DEFAULT LOCAL ROLLBACK SEGMENT
DISABLE QUERY REWRITE
--CREATE OR REPLACE VIEW V_TOS_ONBOARD_CONTAINER
AS
SELECT 
/*+ PARALLEL(DL,4) PARALLEL(LL,4) */      
      NVL(DL.DL_SERVICE,(SELECT ACT_SERVICE_CODE FROM BOOKING_VOYAGE_ROUTING_DTL WHERE BOOKING_NO = LL_FK_BOOKING_NO AND VOYAGE_SEQNO = LL_FK_BKG_VOYAGE_ROUTING_DTL)) DL_SERVICE
      ,NVL(DL.DL_VESSEL,(SELECT ACT_VESSEL_CODE FROM BOOKING_VOYAGE_ROUTING_DTL WHERE BOOKING_NO = LL_FK_BOOKING_NO AND VOYAGE_SEQNO = LL_FK_BKG_VOYAGE_ROUTING_DTL)) DL_VESSEL
      ,NVL(DL.DL_VOYAGE,(SELECT ACT_VOYAGE_NUMBER FROM BOOKING_VOYAGE_ROUTING_DTL WHERE BOOKING_NO = LL_FK_BOOKING_NO AND VOYAGE_SEQNO = LL_FK_BKG_VOYAGE_ROUTING_DTL)) DL_VOYAGE
      ,NVL(DL.DL_DIRECTION,(SELECT ACT_PORT_DIRECTION FROM BOOKING_VOYAGE_ROUTING_DTL WHERE BOOKING_NO = LL_FK_BOOKING_NO AND VOYAGE_SEQNO = LL_FK_BKG_VOYAGE_ROUTING_DTL)) DL_DIRECTION      
      ,NVL(DL.DL_PORT_SEQ,(SELECT ACT_PORT_SEQUENCE FROM BOOKING_VOYAGE_ROUTING_DTL WHERE BOOKING_NO = LL_FK_BOOKING_NO AND VOYAGE_SEQNO = LL_FK_BKG_VOYAGE_ROUTING_DTL)) DL_PORT_SEQ
      ,LL.LL_FK_BOOKING_NO
      ,LL.LL_DN_EQUIPMENT_NO
      ,LL.LL_POL
      ,NVL(DL.DL_POD,(SELECT DISCHARGE_PORT FROM BOOKING_VOYAGE_ROUTING_DTL WHERE BOOKING_NO = LL_FK_BOOKING_NO AND VOYAGE_SEQNO = LL_FK_BKG_VOYAGE_ROUTING_DTL)) DL_POD
      ,TO_DATE(NVL(DL.DL_ETA,(SELECT TO_CHAR(ARRIVAL_DATE) FROM BOOKING_VOYAGE_ROUTING_DTL WHERE BOOKING_NO = LL_FK_BOOKING_NO AND VOYAGE_SEQNO = LL_FK_BKG_VOYAGE_ROUTING_DTL)),'DD/MM/YYYY HH24:MI') DL_ETA
      ,TO_DATE(LL.LL_ETD,'DD/MM/YYYY HH24:MI') LL_ETD
      ,LL.LL_DN_SHIPMENT_TYP
      ,LL.LL_DN_SOC_COC
      ,LL.LL_DN_FINAL_POD
      ,LL.LL_DN_NXT_POD1
      ,LL.LL_DN_NXT_POD2
      ,LL.LL_DN_NXT_POD3
      ,LL.LL_LOAD_CONDITION
      ,LL.LL_CONTAINER_GROSS_WEIGHT
      ,LL.LL_OVERLENGTH_FRONT_CM
      ,LL.LL_OVERLENGTH_REAR_CM
      ,LL.LL_OVERWIDTH_RIGHT_CM
      ,LL.LL_OVERWIDTH_LEFT_CM
      ,LL.LL_OVERHEIGHT_CM
      ,LL.LL_REEFER_TMP
      ,LL.LL_REEFER_TMP_UNIT
      ,LL.LL_DN_HUMIDITY
      ,LL.LL_DN_VENTILATION
      ,LL.LL_FLASH_POINT
      ,LL.LL_FLASH_UNIT
      ,LL.LL_FK_IMDG
      ,LL.LL_FK_UNNO
      ,DL.DL_STOWAGE_POSITION
      ,LL.LL_STOWAGE_POSITION
      ,LL.LL_FK_HANDLING_INSTRUCTION_1
      ,LL.LL_FK_HANDLING_INSTRUCTION_2
      ,LL.LL_FK_HANDLING_INSTRUCTION_3
      ,LL.LL_CONTAINER_LOADING_REM_1
      ,LL.LL_CONTAINER_LOADING_REM_2
      ,LL.LL_RESIDUE_ONLY_FLAG
      ,LL.LL_DN_EQ_SIZE
      ,LL.LL_DN_EQ_TYPE
      ,LL.LL_FK_PORT_CLASS
      ,LL.LL_ACTIVITY_DATE_TIME
      ,DL.DL_ACTIVITY_DATE_TIME
      ,LL.LL_RECORD_STATUS
      ,LL.LL_LL_RECORD_STATUS
      ,DL.DL_RECORD_STATUS
      ,DL.DL_DL_RECORD_STATUS
      ,LL.LL_FK_LOAD_LIST_ID
      ,DL.DL_FK_DISCHARGE_LIST_ID
      ,LL.LL_LOAD_LIST_STATUS
      ,DL.DL_DISCHARGE_LIST_STATUS 
      ,LL.LL_VESSEL     
      ,NVL(DL.DL_DN_TERMINAL,(SELECT TO_TERMINAL FROM BOOKING_VOYAGE_ROUTING_DTL WHERE BOOKING_NO = LL_FK_BOOKING_NO AND VOYAGE_SEQNO = LL_FK_BKG_VOYAGE_ROUTING_DTL)) DL_DN_TERMINAL  
      ,LL.LL_DN_TERMINAL
      ,NVL(DL.DL_POD_TERMINAL,(SELECT TO_TERMINAL FROM BOOKING_VOYAGE_ROUTING_DTL WHERE BOOKING_NO = LL_FK_BOOKING_NO AND VOYAGE_SEQNO = LL_FK_BKG_VOYAGE_ROUTING_DTL)) DL_POD_TERMINAL
      ,NVL(DL.DL_DN_POL_TERMINAL,(SELECT FROM_TERMINAL FROM BOOKING_VOYAGE_ROUTING_DTL WHERE BOOKING_NO = LL_FK_BOOKING_NO AND VOYAGE_SEQNO = LL_FK_BKG_VOYAGE_ROUTING_DTL)) DL_DN_POL_TERMINAL
      ,LL.LL_DN_DISCHARGE_TERMINAL
      ,NVL(DL.DL_CONTAINER_SEQ_NO,LL.LL_CONTAINER_SEQ_NO)
      ,LL.LL_CONTAINER_SEQ_NO
      ,NVL(DL.DL_FK_SLOT_OPERATOR,LL.LL_FK_SLOT_OPERATOR)
      ,NVL(DL.DL_FK_CONTAINER_OPERATOR,LL.LL_FK_CONTAINER_OPERATOR)
      ,LL.LL_FK_SLOT_OPERATOR
      ,LL.LL_FK_CONTAINER_OPERATOR
      ,LL.LL_LOADING_STATUS --##02
      ,DL.DL_DISCHARGE_STATUS --##02
      ,DL.DL_OUT_SLOT_OPERATOR          --BAYPLAN CHANGES 18,AUGUST,2011
      ,LL.LL_FK_BKG_VOYAGE_ROUTING_DTL  --BAYPLAN CHANGES 18,AUGUST,2011
      ,LL.LL_FINAL_DEST                 --BAYPLAN CHANGES 18,AUGUST,2011
      ,LL.LL_DN_DISCHARGE_PORT          --BAYPLAN CHANGES 18,AUGUST,2011
      ,LL.LL_DN_FULL_MT 		--BAYPLAN CHANGES 18,AUGUST,2011
      ,LL.LL_MLO_DEL  --##06
      ,DL.DL_MLO_DEL  --##06
      ,LL.LL_MLO_POD1 --##07
      ,DL.DL_MLO_POD1 --##07
FROM VASAPPS.V_TOS_LL_CONTAINER LL
,VASAPPS.V_TOS_DL_CONTAINER DL
WHERE  LL.LL_VESSEL    	 			   = DL.DL_VESSEL(+)
AND    LL.LL_BOOKING_NO				   = DL.DL_FK_BOOKING_NO(+)
AND    LL.LL_FK_BKG_SIZE_TYPE_DTL	   = DL.DL_FK_BKG_SIZE_TYPE_DTL(+)
AND    LL.LL_FK_BKG_SUPPLIER		   = DL.DL_FK_BKG_SUPPLIER(+)
AND    LL.LL_FK_BKG_EQUIPM_DTL		   = DL.DL_FK_BKG_EQUIPM_DTL(+)
AND    LL.LL_FK_BKG_VOYAGE_ROUTING_DTL = DL.DL_FK_BKG_VOYAGE_ROUTING_DTL(+)
AND   (LL.LL_LOADING_STATUS IN ('LO','RB') OR LL.LL_LOADING_STATUS IS NULL) --##03, ##004
;