CREATE OR REPLACE VIEW V_TOS_DL_CONTAINER
AS
SELECT DL_SERVICE
      ,DL_VESSEL
      ,DL_VOYAGE
      ,DL_DIRECTION      
      ,DL_PORT_SEQ 
      ,DL_POD       
      ,DL_ETA      
      ,DL_PK_BOOKED_DISCHARGE_ID
      ,DL_FK_DISCHARGE_LIST_ID
      ,DL_CONTAINER_SEQ_NO
      ,DL_FK_BOOKING_NO      
      ,DL_FK_BKG_SIZE_TYPE_DTL
      ,DL_FK_BKG_SUPPLIER
      ,DL_FK_BKG_EQUIPM_DTL
      ,DL_DN_EQUIPMENT_NO
      ,DL_FK_BKG_VOYAGE_ROUTING_DTL
      ,DL_DN_EQ_SIZE
      ,DL_DN_EQ_TYPE
      ,DL_DN_FULL_MT
      ,DL_DN_BKG_TYP
      ,DL_DN_SOC_COC
      ,DL_DN_SHIPMENT_TERM
      ,DL_DN_SHIPMENT_TYP
      ,DL_LOCAL_STATUS
      ,DL_LOCAL_TERMINAL_STATUS
      ,DL_MIDSTREAM_HANDLING_CODE
      ,DL_LOAD_CONDITION
      ,DL_DN_LOADING_STATUS
      ,DL_DISCHARGE_STATUS
      ,DL_STOWAGE_POSITION
      ,TO_CHAR(DL_ACTIVITY_DATE_TIME,'DD/MM/YYYY') DL_ACTIVITY_DATE_TIME
      ,DL_CONTAINER_GROSS_WEIGHT
      ,DL_DAMAGED
      ,DL_VOID_SLOT
      ,DL_FK_SLOT_OPERATOR
      ,DL_FK_CONTAINER_OPERATOR
      ,DL_OUT_SLOT_OPERATOR
      ,DL_DN_SPECIAL_HNDL
      ,DL_SEAL_NO
      ,DL_DN_POL
      ,DL_DN_POL_TERMINAL
      ,DL_DN_NXT_POD1
      ,DL_DN_NXT_POD2
      ,DL_DN_NXT_POD3
      ,DL_DN_FINAL_POD
      ,DL_FINAL_DEST
      ,DL_DN_NXT_SRV
      ,DL_DN_NXT_VESSEL
      ,DL_DN_NXT_VOYAGE
      ,DL_DN_NXT_DIR
      ,DL_MLO_VESSEL
      ,DL_MLO_VOYAGE
      ,DL_MLO_VESSEL_ETA
      ,DL_MLO_POD1
      ,DL_MLO_POD2
      ,DL_MLO_POD3
      ,DL_MLO_DEL
      ,DL_SWAP_CONNECTION_ALLOWED
      ,DL_FK_HANDLING_INSTRUCTION_1
      ,DL_FK_HANDLING_INSTRUCTION_2
      ,DL_FK_HANDLING_INSTRUCTION_3
      ,DL_CONTAINER_LOADING_REM_1
      ,DL_CONTAINER_LOADING_REM_2
      ,DL_FK_SPECIAL_CARGO
      ,DL_TIGHT_CONNECTION_FLAG1
      ,DL_TIGHT_CONNECTION_FLAG2
      ,DL_TIGHT_CONNECTION_FLAG3
      ,DL_FK_IMDG
      ,DL_FK_UNNO
      ,DL_FK_UN_VAR
      ,DL_FK_PORT_CLASS
      ,DL_FK_PORT_CLASS_TYP
      ,DL_FLASH_UNIT
      ,DL_FLASH_POINT
      ,DL_FUMIGATION_ONLY
      ,DL_RESIDUE_ONLY_FLAG
      ,DL_OVERHEIGHT_CM
      ,DL_OVERWIDTH_LEFT_CM
      ,DL_OVERWIDTH_RIGHT_CM
      ,DL_OVERLENGTH_FRONT_CM
      ,DL_OVERLENGTH_REAR_CM
      ,DL_REEFER_TEMPERATURE
      ,DL_REEFER_TMP_UNIT
      ,DL_DN_HUMIDITY
      ,DL_DN_VENTILATION
      ,DL_PUBLIC_REMARK
      ,DL_RECORD_STATUS
      ,DL_RECORD_ADD_USER   
      ,DL_RECORD_ADD_DATE   
      ,DL_RECORD_CHANGE_USER
      ,DL_RECORD_CHANGE_DATE
      ,DL_DL_RECORD_STATUS
      ,DL_DISCHARGE_LIST_STATUS
      ,DL_PK_DISCHARGE_LIST_ID
      ,DL_DN_SERVICE_GROUP_CODE
      ,DL_FK_VERSION
      ,DL_DN_TERMINAL
      ,DL_DA_BOOKED_TOT          
      ,DL_DA_DISCHARGED_TOT      
      ,DL_DA_ROB_TOT             
      ,DL_DA_OVERLANDED_TOT      
      ,DL_DA_SHORTLANDED_TOT     
      ,DL_DL_RECORD_ADD_USER     
      ,DL_DL_RECORD_ADD_DATE     
      ,DL_DL_RECORD_CHANGE_USER  
      ,DL_DL_RECORD_CHANGE_DATE       
      ,DL_POD_DATE	
      ,DL_POD_TIME
      ,DL_POD_TERMINAL	                 
      ,DL_OOG_OW
      ,DL_OOG_OL      
      ,DL_ETD
FROM V_TOS_DL_CONTAINER_EZLL  TDCE
    ,V_DL_PORT_CALL_EZLL      DPCE
WHERE TDCE.DL_POD           = DPCE.PORT
  AND TDCE.DL_POD_TERMINAL  = DPCE.TERMINAL
  AND TDCE.DL_SERVICE       = DPCE.SERVICE
  AND TDCE.DL_VESSEL        = DPCE.VESSEL
  AND TDCE.DL_VOYAGE        = DPCE.VOYAGE
  AND TDCE.DL_DIRECTION     = DPCE.DIRECTION
  AND TDCE.DL_PORT_SEQ      = DPCE.PORT_SEQ
UNION ALL
SELECT DL_SERVICE
      ,DL_VESSEL
      ,DL_VOYAGE
      ,DL_DIRECTION      
      ,DL_PORT_SEQ 
      ,DL_POD       
      ,DL_ETA      
      ,NULL DL_PK_BOOKED_DISCHARGE_ID
      ,NULL DL_FK_DISCHARGE_LIST_ID
      ,DL_CONTAINER_SEQ_NO
      ,DL_FK_BOOKING_NO      
      ,NULL DL_FK_BKG_SIZE_TYPE_DTL
      ,NULL DL_FK_BKG_SUPPLIER
      ,NULL DL_FK_BKG_EQUIPM_DTL
      ,DL_DN_EQUIPMENT_NO
      ,NULL DL_FK_BKG_VOYAGE_ROUTING_DTL
      ,DL_DN_EQ_SIZE
      ,DL_DN_EQ_TYPE
      ,DL_DN_FULL_MT
      ,NULL DL_DN_BKG_TYP
      ,DL_DN_SOC_COC
      ,DL_DN_SHIPMENT_TERM
      ,DL_DN_SHIPMENT_TYP
      ,DL_LOCAL_STATUS
      ,DL_LOCAL_TERMINAL_STATUS
      ,NULL DL_MIDSTREAM_HANDLING_CODE
      ,NULL DL_LOAD_CONDITION
      ,NULL DL_DN_LOADING_STATUS
      ,DL_DISCHARGE_STATUS
      ,DL_STOWAGE_POSITION
      ,NULL DL_ACTIVITY_DATE_TIME
      ,NULL DL_CONTAINER_GROSS_WEIGHT
      ,NULL DL_DAMAGED
      ,DL_VOID_SLOT
      ,DL_FK_SLOT_OPERATOR
      ,DL_FK_CONTAINER_OPERATOR
      ,DL_OUT_SLOT_OPERATOR
      ,NULL DL_DN_SPECIAL_HNDL
      ,NULL DL_SEAL_NO
      ,NULL DL_DN_POL
      ,DL_DN_POL_TERMINAL
      ,DL_DN_NXT_POD1
      ,DL_DN_NXT_POD2
      ,DL_DN_NXT_POD3
      ,NULL DL_DN_FINAL_POD
      ,DL_FINAL_DEST
      ,NULL DL_DN_NXT_SRV
      ,NULL DL_DN_NXT_VESSEL
      ,NULL DL_DN_NXT_VOYAGE
      ,NULL DL_DN_NXT_DIR
      ,NULL DL_MLO_VESSEL
      ,NULL DL_MLO_VOYAGE
      ,NULL DL_MLO_VESSEL_ETA
      ,NULL DL_MLO_POD1
      ,NULL DL_MLO_POD2
      ,NULL DL_MLO_POD3
      ,NULL DL_MLO_DEL
      ,NULL DL_SWAP_CONNECTION_ALLOWED
      ,DL_FK_HANDLING_INSTRUCTION_1
      ,DL_FK_HANDLING_INSTRUCTION_2
      ,DL_FK_HANDLING_INSTRUCTION_3           
      ,DL_CONTAINER_LOADING_REM_1
      ,DL_CONTAINER_LOADING_REM_2 
      ,DL_FK_SPECIAL_CARGO
      ,DL_TIGHT_CONNECTION_FLAG1
      ,NULL DL_TIGHT_CONNECTION_FLAG2
      ,NULL DL_TIGHT_CONNECTION_FLAG3
      ,DL_FK_IMDG
      ,DL_FK_UNNO
      ,DL_FK_UN_VAR
      ,DL_FK_PORT_CLASS
      ,NULL DL_FK_PORT_CLASS_TYP
      ,DL_FLASH_UNIT 
      ,DL_FLASH_POINT
      ,NULL DL_FUMIGATION_ONLY
      ,NULL DL_RESIDUE_ONLY_FLAG
      ,DL_OVERHEIGHT_CM
      ,DL_OVERWIDTH_LEFT_CM
      ,DL_OVERWIDTH_RIGHT_CM
      ,DL_OVERLENGTH_FRONT_CM
      ,DL_OVERLENGTH_REAR_CM
      ,DL_REEFER_TEMPERATURE
      ,DL_REEFER_TMP_UNIT
      ,NULL DL_DN_HUMIDITY
      ,NULL DL_DN_VENTILATION
      ,NULL DL_PUBLIC_REMARK
      ,NULL DL_RECORD_STATUS
      ,NULL DL_RECORD_ADD_USER   
      ,NULL DL_RECORD_ADD_DATE   
      ,NULL DL_RECORD_CHANGE_USER
      ,NULL DL_RECORD_CHANGE_DATE
      ,NULL DL_DL_RECORD_STATUS
      ,DL_DISCHARGE_LIST_STATUS
      ,NULL DL_PK_DISCHARGE_LIST_ID
      ,NULL DL_DN_SERVICE_GROUP_CODE
      ,NULL DL_FK_VERSION
      ,NULL DL_DN_TERMINAL
      ,NULL DL_DA_BOOKED_TOT        
      ,NULL DL_DA_DISCHARGED_TOT    
      ,NULL DL_DA_ROB_TOT           
      ,NULL DL_DA_OVERLANDED_TOT    
      ,NULL DL_DA_SHORTLANDED_TOT   	
      ,NULL DL_DL_RECORD_ADD_USER   
      ,NULL DL_DL_RECORD_ADD_DATE   	                            
      ,NULL DL_DL_RECORD_CHANGE_USER	  
      ,NULL DL_DL_RECORD_CHANGE_DATE
      ,DL_POD_DATE
      ,DL_POD_TIME
      ,DL_POD_TERMINAL
      ,TO_CHAR(DL_OOG_OW)    DL_OOG_OW
      ,TO_CHAR(DL_OOG_OL)    DL_OOG_OL                        
      ,NULL DL_ETD
FROM V_TOS_DL_CONTAINER_SL  DCS 
    ,V_DL_PORTCALL_SL       DPS    
WHERE DCS.DL_POD           = DPS.PORT
  AND DCS.DL_POD_TERMINAL  = DPS.TERMINAL
  AND DCS.DL_SERVICE       = DPS.SERVICE
  AND DCS.DL_VESSEL        = DPS.VESSEL
  AND DCS.DL_VOYAGE        = DPS.VOYAGE
  AND DCS.DL_DIRECTION     = DPS.DIRECTION
  AND DCS.DL_PORT_SEQ      = DPS.PORT_SEQ;