ALTER TABLE TOS_DL_BOOKED_DISCHARGE ADD (  CATEGORY_CODE VARCHAR2(10 CHAR) ,FIRST_LEG_FLAG VARCHAR(1CHAR)) ; 

ALTER TABLE TOS_DL_BOOKED_DISCHARGE_TMP ADD (  CATEGORY_CODE VARCHAR2(10 CHAR),FIRST_LEG_FLAG VARCHAR(1CHAR)) ; 

ALTER TABLE TOS_LL_BOOKED_LOADING ADD ( CATEGORY_CODE VARCHAR2(10 CHAR) ,FIRST_LEG_FLAG VARCHAR(1CHAR)) ; 

ALTER TABLE TOS_LL_BOOKED_LOADING_TMP ADD (  CATEGORY_CODE VARCHAR2(10 CHAR),FIRST_LEG_FLAG VARCHAR(1CHAR)) ; 








