ALTER TABLE TOS_DL_BOOKED_DISCHARGE_TMP MODIFY (CATEGORY_CODE VARCHAR2(70 CHAR));

ALTER TABLE TOS_DL_BOOKED_DISCHARGE MODIFY (CATEGORY_CODE VARCHAR2(70 CHAR));

ALTER TABLE TOS_LL_BOOKED_LOADING_TMP MODIFY (CATEGORY_CODE VARCHAR2(70 CHAR));

ALTER TABLE TOS_LL_BOOKED_LOADING MODIFY (CATEGORY_CODE VARCHAR2(70 CHAR));

