--ll
UPDATE ZCV_VIEW_COLUMN ZVC
SET ZVC.COLUMN_SEQ = ZVC.COLUMN_SEQ+2,
       ZVC.RECORD_CHANGE_USER = 'DEV_TEAM',
       ZVC.RECORD_CHANGE_DATE = SYSDATE
WHERE ZVC.FK_VIEW_ID          = 14 
AND ZVC.RECORD_STATUS       = 'A'
AND ZVC.COLUMN_SEQ > 16;

--dl
UPDATE ZCV_VIEW_COLUMN ZVC
SET ZVC.COLUMN_SEQ = ZVC.COLUMN_SEQ+2,
       ZVC.RECORD_CHANGE_USER = 'DEV_TEAM',
       ZVC.RECORD_CHANGE_DATE = SYSDATE
WHERE ZVC.FK_VIEW_ID          = 3 
AND ZVC.RECORD_STATUS       = 'A'
AND ZVC.COLUMN_SEQ > 16;

COMMIT;