-- ll
MERGE INTO ZCV_SCREEN_COLUMN TAB
USING (
SELECT  ZSC.PK_SCREEN_COLUMN_ID,
               ZSC.DEFAULT_POSITION,
               ZVC.COLUMN_SEQ         SHOW_POSITION
        FROM  ZCV_SCREEN_COLUMN ZSC,
              ZCV_VIEW_COLUMN   ZVC
        WHERE ZSC.PK_SCREEN_COLUMN_ID = ZVC.FK_SCREEN_COLUMN_ID
        AND   ZVC.FK_VIEW_ID          = 14
        AND   ZVC.RECORD_STATUS       = 'A'  -- Active
        AND   ZVC.COLUMN_SEQ <> ZSC.DEFAULT_POSITION
        ORDER BY ZVC.COLUMN_SEQ
        ) SRC
ON (TAB.PK_SCREEN_COLUMN_ID = SRC.PK_SCREEN_COLUMN_ID)      
WHEN MATCHED THEN
UPDATE SET TAB.DEFAULT_POSITION = SRC.SHOW_POSITION ;

-- dl
-- ll
MERGE INTO ZCV_SCREEN_COLUMN TAB
USING (
SELECT  ZSC.PK_SCREEN_COLUMN_ID,
               ZSC.DEFAULT_POSITION,
               ZVC.COLUMN_SEQ         SHOW_POSITION
        FROM  ZCV_SCREEN_COLUMN ZSC,
              ZCV_VIEW_COLUMN   ZVC
        WHERE ZSC.PK_SCREEN_COLUMN_ID = ZVC.FK_SCREEN_COLUMN_ID
        AND   ZVC.FK_VIEW_ID          = 3
        AND   ZVC.RECORD_STATUS       = 'A'  -- Active
        AND   ZVC.COLUMN_SEQ <> ZSC.DEFAULT_POSITION
        ORDER BY ZVC.COLUMN_SEQ
        ) SRC
ON (TAB.PK_SCREEN_COLUMN_ID = SRC.PK_SCREEN_COLUMN_ID)      
WHEN MATCHED THEN
UPDATE SET TAB.DEFAULT_POSITION = SRC.SHOW_POSITION ;

COMMIT;