CREATE TABLE "VASAPPS"."TOS_LL_DL_ERROR_LOG" 
   (	"EXPORT_IMPORT" VARCHAR2(1) NOT NULL ENABLE, 
	"FK_LL_DL_LIST_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"FK_BOOKING_NO" VARCHAR2(17), 
	"FK_EQUIPMENT_NO" VARCHAR2(12), 
	"ERROR_MSG" VARCHAR2(500), 
	"RECORD_ADD_USER" VARCHAR2(10) NOT NULL ENABLE, 
	"RECORD_ADD_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"EMS_ACTIVITY_CODE" VARCHAR2(5), 
	"EMS_ACTIVITY_DATE" NUMBER(8,0), 
	"EMS_TERMINAL_CODE" VARCHAR2(5), 
	"EMS_SERVICE" VARCHAR2(5), 
	"EMS_VESSEL" VARCHAR2(5), 
	"EMS_VOYAGE" VARCHAR2(10), 
	"PK_LOG_SEQ" NUMBER, 
	 CONSTRAINT "PKR_TOS_TLD01" PRIMARY KEY ("PK_LOG_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "VASDATA"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 10485760 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "VASDATA" ;
 
   COMMENT ON COLUMN "VASAPPS"."TOS_LL_DL_ERROR_LOG"."EXPORT_IMPORT" IS 'Mandatory, E=Export, I=Import';
 
   COMMENT ON COLUMN "VASAPPS"."TOS_LL_DL_ERROR_LOG"."FK_LL_DL_LIST_ID" IS 'Mandatory, FK to TOS_LL_LOAD_LIST in case of export and FK to TOS_DL_DISCHARGE_LIST in case of import';
 
   COMMENT ON COLUMN "VASAPPS"."TOS_LL_DL_ERROR_LOG"."FK_BOOKING_NO" IS 'Optional, Booking No., FK to TOS_LL_BOOKED_LOADING or TOS_DL_BOOKED_DISCHARGE';
 
   COMMENT ON COLUMN "VASAPPS"."TOS_LL_DL_ERROR_LOG"."FK_EQUIPMENT_NO" IS 'Optional, Equipment No., FK to TOS_LL_BOOKED_LOADING or TOS_DL_BOOKED_DISCHARGE';
 
   COMMENT ON COLUMN "VASAPPS"."TOS_LL_DL_ERROR_LOG"."ERROR_MSG" IS 'Optional, Error message';
 
   COMMENT ON COLUMN "VASAPPS"."TOS_LL_DL_ERROR_LOG"."RECORD_ADD_USER" IS 'Mandatory, Create By - Mandatory,Created By ';
 
   COMMENT ON COLUMN "VASAPPS"."TOS_LL_DL_ERROR_LOG"."RECORD_ADD_DATE" IS 'Mandatory, Record add date ';
 
   COMMENT ON COLUMN "VASAPPS"."TOS_LL_DL_ERROR_LOG"."EMS_ACTIVITY_CODE" IS 'Optional, Activity Code, FK to ECP030';
 
   COMMENT ON COLUMN "VASAPPS"."TOS_LL_DL_ERROR_LOG"."EMS_ACTIVITY_DATE" IS 'Optional, Activity Date';
 
   COMMENT ON COLUMN "VASAPPS"."TOS_LL_DL_ERROR_LOG"."EMS_TERMINAL_CODE" IS 'Optional, Terminal code in ECP030';
 
   COMMENT ON COLUMN "VASAPPS"."TOS_LL_DL_ERROR_LOG"."EMS_SERVICE" IS 'Optional, Service Code, FK to ECP030.MQSVCE';
 
   COMMENT ON COLUMN "VASAPPS"."TOS_LL_DL_ERROR_LOG"."EMS_VESSEL" IS 'Optional, Vessel Code, FK to ECP030.MQVESS';
 
   COMMENT ON COLUMN "VASAPPS"."TOS_LL_DL_ERROR_LOG"."EMS_VOYAGE" IS 'Optional, Voyage number, FK to ECP030.MQVOYN';
 
   COMMENT ON COLUMN "VASAPPS"."TOS_LL_DL_ERROR_LOG"."PK_LOG_SEQ" IS 'Mandatory, Promary Key, Auto Increment by VASAPPS.SR_TOS_TLD01';
 
   COMMENT ON TABLE "VASAPPS"."TOS_LL_DL_ERROR_LOG"  IS 'This table store error message from EMS validation in EZLL and EZDL';
 
  GRANT SELECT ON "VASAPPS"."TOS_LL_DL_ERROR_LOG" TO "RCLAPPS";