DROP TABLE VASAPPS.EZLL_GBL_PORT_MASTER;

CREATE TABLE VASAPPS.EZLL_GBL_PORT_MASTER
(
  PK_EZLL_PORT_MASTER  NUMBER                   NOT NULL,
  COUNTRY_CODE         VARCHAR2(30 BYTE)        NOT NULL,
  PORT_CODE            VARCHAR2(30 BYTE)        NOT NULL,
  RECORD_STATUS        VARCHAR2(1 BYTE)         NOT NULL,
  RECORD_ADD_BY        VARCHAR2(20 BYTE)        NOT NULL,
  RECORD_ADD_DATE      DATE                     NOT NULL,
  RECORD_UPDATE_BY     VARCHAR2(20 BYTE),
  RECORD_UPDATE_DATE   DATE
)
TABLESPACE VASDATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          10M
            NEXT             10M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN VASAPPS.EZLL_GBL_PORT_MASTER.RECORD_STATUS IS 'A = Active, S = Suspended';


CREATE UNIQUE INDEX VASAPPS.EZLL_GBL_PORT_MASTER_PK ON VASAPPS.EZLL_GBL_PORT_MASTER
(PORT_CODE)
LOGGING
TABLESPACE VASDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          10M
            NEXT             10M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE VASAPPS.EZLL_GBL_PORT_MASTER ADD (
  CONSTRAINT EZLL_GBL_PORT_MASTER_PK
 PRIMARY KEY
 (PORT_CODE)
    USING INDEX 
    TABLESPACE VASDATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          10M
                NEXT             10M
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));
               
               
GRANT SELECT ON VASAPPS.EZLL_GBL_PORT_MASTER TO SEALINER, RCLAPPS, VASAPPS_RO;               