CREATE TABLE TOS_LL_DL_BOOKING
(
  PK_TOS_LL_DL_BOOKING_SEQ  INTEGER             NOT NULL,
  FK_BOOKING_NO             VARCHAR2(20 BYTE)   NOT NULL,
  BOOKING_TYPE              VARCHAR2(5 BYTE)   ,
  OLD_BOOKING_STATUS        VARCHAR2(1 BYTE)    ,
  NEW_BOOKING_STATUS        VARCHAR2(1 BYTE)    ,
  SOURCE                    VARCHAR2(5 BYTE)    NOT NULL,
  STATUS                    VARCHAR2(1 BYTE)    NOT NULL,
  ERR_DESC                  VARCHAR2(1000 BYTE),
  RECORD_STATUS             VARCHAR2(1 BYTE)    NOT NULL,
  RECORD_ADD_USER           VARCHAR2(10 BYTE)   NOT NULL,
  RECORD_ADD_DATE           TIMESTAMP(6)        NOT NULL,
  RECORD_CHANGE_USER        VARCHAR2(10 BYTE),
  RECORD_CHANGE_DATE        TIMESTAMP(6),
  EQUIPMENT_NO              VARCHAR2(12 CHAR),
  EQUIPMENT_SEQ             NUMBER(12),
  CATEGORY_CODE             VARCHAR2(70 CHAR),
  VGM                                NUMBER(14,2),
  SEA_LEG_PORT                VARCHAR2(5 CHAR),
  FK_SERVICE   VARCHAR2( 5 CHAR),
  FK_VESSEL   VARCHAR2( 5 CHAR),
  FK_VOYAGE VARCHAR2( 10 CHAR),
  FK_DIRECTION VARCHAR2( 2 CHAR),
  FK_PORT_SEQ NUMBER(5)
);

COMMENT ON TABLE TOS_LL_DL_BOOKING IS 'KEEP BOOKING THAT NEED TO FLOW DATA TO EZLL/EZDL ';

COMMENT ON COLUMN TOS_LL_DL_BOOKING.PK_TOS_LL_DL_BOOKING_SEQ IS 'MANDATORY BOOKING TO EZLL SEQ, PRIMARY KEY  AUTO INCREASEMENT : SR_TOS_BZS01';

COMMENT ON COLUMN TOS_LL_DL_BOOKING.FK_BOOKING_NO IS 'Mandatory, Booking No, FK to BKP001.BABKNO';

COMMENT ON COLUMN TOS_LL_DL_BOOKING.BOOKING_TYPE IS 'Optional, Booking Type';

COMMENT ON COLUMN TOS_LL_DL_BOOKING.OLD_BOOKING_STATUS IS 'Optional, Old Booking Status ';

COMMENT ON COLUMN TOS_LL_DL_BOOKING.NEW_BOOKING_STATUS IS 'Optional, New Booking Status ';

COMMENT ON COLUMN TOS_LL_DL_BOOKING.SOURCE IS 'Mandatory, Source  Vlaues : BKG - Data will flow to EZLL/EZDL, LLDL - Datat will flow back to Booking. ';

COMMENT ON COLUMN TOS_LL_DL_BOOKING.STATUS IS 'Mandatory, STATUS Vlaues : P - PENDING, E - ERROR , C - COMPLETE  ';

COMMENT ON COLUMN TOS_LL_DL_BOOKING.ERR_DESC IS 'Mandatory, ERROR DESCRIPTION';

COMMENT ON COLUMN TOS_LL_DL_BOOKING.RECORD_STATUS IS 'Mandatory, Record Status, Values : A - Active , S - Suspened';

COMMENT ON COLUMN TOS_LL_DL_BOOKING.RECORD_ADD_USER IS 'Mandatory, Record Add user ';

COMMENT ON COLUMN TOS_LL_DL_BOOKING.RECORD_ADD_DATE IS 'Mandatory, Record Add Date ';

COMMENT ON COLUMN TOS_LL_DL_BOOKING.RECORD_CHANGE_USER IS 'Optional, Record Change User ';

COMMENT ON COLUMN TOS_LL_DL_BOOKING.RECORD_CHANGE_DATE IS 'Optional, Record Change Date ';

COMMENT ON COLUMN TOS_LL_DL_BOOKING.EQUIPMENT_NO IS 'Optional, From BKP009.BICTRN ';

COMMENT ON COLUMN TOS_LL_DL_BOOKING.EQUIPMENT_SEQ IS 'Optional, From BKP009.BISEQN ';

COMMENT ON COLUMN TOS_LL_DL_BOOKING.CATEGORY_CODE IS 'Optional, From BKP009.EQP_CATEGORY ';

COMMENT ON COLUMN TOS_LL_DL_BOOKING.SEA_LEG_PORT IS 'Optional, From BKP001.BAPOL';