CREATE TABLE EDI_TRANSACTION_DETAIL_TMP
(
  MSG_REFERENCE       VARCHAR2(17 BYTE)         NOT NULL,
  EDI_ETD_UID         NUMBER(16)                NOT NULL,
  OLD_STATUS          VARCHAR2(3 BYTE),
  NEW_STATUS          VARCHAR2(3 BYTE),
  RECORD_STATUS       VARCHAR2(1 BYTE)          NOT NULL,
  RECORD_CHANGE_USER  VARCHAR2(10 BYTE),
  RECORD_CHANGE_DATE  DATE
)