CREATE TABLE EDI_TRANSACTION_HEADER_TMP
(
  MODULE              VARCHAR2(10 BYTE),
  DIRECTION           VARCHAR2(3 BYTE)          NOT NULL,
  MSG_REFERENCE       VARCHAR2(17 BYTE)         NOT NULL,
  OLD_STATUS          VARCHAR2(3 BYTE),
  NEW_STATUS          VARCHAR2(3 BYTE),
  RECORD_STATUS       VARCHAR2(1 BYTE)          NOT NULL,
  RECORD_CHANGE_USER  VARCHAR2(10 BYTE),
  RECORD_CHANGE_DATE  DATE
)