 CREATE TABLE ECM_LOOKUP_CONFIG_MST 
   (	"MASTER_CD" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"MASTER_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"LIST_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"FINDIN_FIELD_CD" VARCHAR2(1000 BYTE), 
	"FINDIN_FIELD_DESC" VARCHAR2(1000 BYTE), 
	"SORTBY_FIELD_CD" VARCHAR2(1000 BYTE), 
	"SORTBY_FIELD_DESC" VARCHAR2(1000 BYTE), 
	"NO_OF_COLUMN" NUMBER(2,0) NOT NULL ENABLE, 
	"COLUMN_NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"PRE_CONDITION" VARCHAR2(100 BYTE), 
	"MASTER_SQL" VARCHAR2(2000 BYTE) NOT NULL ENABLE, 
	"CREATE_BY" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"CREATE_DT" DATE NOT NULL ENABLE, 
	"UPD_BY" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"UPD_DT" DATE NOT NULL ENABLE
   );
   
   
ALTER TABLE ECM_LOOKUP_CONFIG_MST ADD CONSTRAINT "PKV_VLCZ51" PRIMARY KEY ("MASTER_CD");

 

   COMMENT ON COLUMN ECM_LOOKUP_CONFIG_MST.MASTER_CD IS 'Master Code';
 
   COMMENT ON COLUMN ECM_LOOKUP_CONFIG_MST.MASTER_NAME IS 'Master Description';
 
   COMMENT ON COLUMN ECM_LOOKUP_CONFIG_MST.LIST_NAME IS 'List Name';
 
   COMMENT ON COLUMN ECM_LOOKUP_CONFIG_MST.FINDIN_FIELD_CD IS 'Find in on Code';
 
   COMMENT ON COLUMN ECM_LOOKUP_CONFIG_MST.FINDIN_FIELD_DESC IS 'Find in on Description';
 
   COMMENT ON COLUMN ECM_LOOKUP_CONFIG_MST.SORTBY_FIELD_CD IS 'Sort By on Code';
 
   COMMENT ON COLUMN ECM_LOOKUP_CONFIG_MST.SORTBY_FIELD_DESC IS 'Sort BY on Description';
 
   COMMENT ON COLUMN ECM_LOOKUP_CONFIG_MST.NO_OF_COLUMN IS 'No of columns';
 
   COMMENT ON COLUMN ECM_LOOKUP_CONFIG_MST.COLUMN_NAME IS 'Coulmn Description';
 
   COMMENT ON COLUMN ECM_LOOKUP_CONFIG_MST.PRE_CONDITION IS 'Pre Condition';
 
   COMMENT ON COLUMN ECM_LOOKUP_CONFIG_MST.MASTER_SQL IS 'Master SQL';
 
   COMMENT ON COLUMN ECM_LOOKUP_CONFIG_MST.CREATE_BY IS 'Create By';
 
   COMMENT ON COLUMN ECM_LOOKUP_CONFIG_MST.CREATE_DT IS 'Create Date Time';
 
   COMMENT ON COLUMN ECM_LOOKUP_CONFIG_MST.UPD_BY IS 'Update By';
 
   COMMENT ON COLUMN ECM_LOOKUP_CONFIG_MST.UPD_DT IS 'Update Date Time';
 
   COMMENT ON TABLE ECM_LOOKUP_CONFIG_MST  IS 'Lookup Configration Master - Lookup Configration Master';
 
