 CREATE TABLE ECM_LOG_TRACE 
   (	PROG_ID VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	PROG_SQL VARCHAR2(4000 BYTE), 
	RECORD_STATUS VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	RECORD_ADD_USER VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	RECORD_ADD_DATE TIMESTAMP (6) NOT NULL ENABLE, 
	RECORD_CHANGE_USER VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	RECORD_CHANGE_DATE TIMESTAMP (6) NOT NULL ENABLE
   )  ;
 

   COMMENT ON COLUMN ECM_LOG_TRACE.PROG_ID IS 'Program id';
 
   COMMENT ON COLUMN ECM_LOG_TRACE.PROG_SQL IS 'Program SQL';
 
   COMMENT ON COLUMN ECM_LOG_TRACE.RECORD_STATUS IS 'Record Status';
 
   COMMENT ON COLUMN ECM_LOG_TRACE.RECORD_ADD_USER IS 'Create By';
 
   COMMENT ON COLUMN ECM_LOG_TRACE.RECORD_ADD_DATE IS 'Create Date Time';
 
   COMMENT ON COLUMN ECM_LOG_TRACE.RECORD_CHANGE_USER IS 'Update By';
 
   COMMENT ON COLUMN ECM_LOG_TRACE.RECORD_CHANGE_DATE IS 'Update Date Time';
 
   COMMENT ON TABLE ECM_LOG_TRACE  IS 'Log Trace - Log Trace';
/
   