--------------------------------------------------------
--  File created - Monday-July-09-2012   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TOS_BOOKING_RETRIGGER
--------------------------------------------------------

  CREATE TABLE "VASAPPS"."TOS_BOOKING_RETRIGGER" 
   (	"BOOKING_NO" VARCHAR2(17 BYTE), 
	"TOTAL_EZLL_CONTAINER" NUMBER, 
	"TOTAL_BOOKING_CONTAINER" NUMBER, 
	"CONTAINER_IN_EACH_LEG" NUMBER, 
	"TOTAL_LEG" NUMBER, 
	"RECORD_STATUS" VARCHAR2(1 BYTE), 
	"RECORD_ADD_USER" VARCHAR2(10 BYTE), 
	"RECORD_ADD_DATE" DATE, 
	"RECORD_CHANGE_USER" VARCHAR2(10 BYTE), 
	"RECORD_CHANGE_DATE" DATE
   )  ;
 

   COMMENT ON COLUMN "VASAPPS"."TOS_BOOKING_RETRIGGER"."TOTAL_EZLL_CONTAINER" IS 'Total container exists in ezll for all legs.';
 
   COMMENT ON COLUMN "VASAPPS"."TOS_BOOKING_RETRIGGER"."TOTAL_BOOKING_CONTAINER" IS 'Total container exists in bookings for all legs.';
 
   COMMENT ON COLUMN "VASAPPS"."TOS_BOOKING_RETRIGGER"."CONTAINER_IN_EACH_LEG" IS 'Total containers in each leg';
 
   COMMENT ON COLUMN "VASAPPS"."TOS_BOOKING_RETRIGGER"."TOTAL_LEG" IS 'Total leg';
--------------------------------------------------------
--  DDL for Index TOS_BOOKING_RETRIGGER_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "VASAPPS"."TOS_BOOKING_RETRIGGER_UK1" ON "VASAPPS"."TOS_BOOKING_RETRIGGER" ("BOOKING_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TOS_BOOKING_RETRIGGER
--------------------------------------------------------

  ALTER TABLE "VASAPPS"."TOS_BOOKING_RETRIGGER" MODIFY ("BOOKING_NO" NOT NULL ENABLE);
 
  ALTER TABLE "VASAPPS"."TOS_BOOKING_RETRIGGER" MODIFY ("RECORD_STATUS" NOT NULL ENABLE);
 
  ALTER TABLE "VASAPPS"."TOS_BOOKING_RETRIGGER" ADD CONSTRAINT "TOS_BOOKING_RETRIGGER_UK1" UNIQUE ("BOOKING_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
