 CREATE TABLE TOS_LOG_INFO_HEADER 
 (PK_LOG_INFO_HEADER_ID   NUMBER             , 
  CALLED_FROM      VARCHAR2(100 BYTE) , 
  CALLING          VARCHAR2(100 BYTE) , 
  SEQ_ID           VARCHAR2(10 BYTE)  , 
  REMARKS          VARCHAR2(1000 BYTE),
  RECORD_ADD_USER  VARCHAR2(10 BYTE)  , 
  RECORD_ADD_DATE  TIMESTAMP(6));
  
   ALTER TABLE TOS_LOG_INFO_HEADER ADD CONSTRAINT PK_LOG_INFO_HEADER PRIMARY KEY (PK_LOG_INFO_HEADER_ID);
 