
  CREATE TABLE TOS_SYNC_ERROR_LOG_BACKUP 
   (	PK_SYNC_ERR_LOG_ID NUMBER(*,0) NOT NULL ENABLE, 
	PARAMETER_STRING VARCHAR2(500 BYTE), 
	PROG_TYPE VARCHAR2(20 BYTE), 
	OPEARTION_TYPE VARCHAR2(1 BYTE), 
	ERROR_MSG VARCHAR2(100 BYTE), 
	RERUN_STATUS NUMBER(1,0), 
	RECORD_STATUS VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	RECORD_ADD_USER VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	RECORD_ADD_DATE TIMESTAMP (6) NOT NULL ENABLE, 
	RECORD_CHANGE_USER VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	RECORD_CHANGE_DATE TIMESTAMP (6) NOT NULL ENABLE, 
	RECORD_FILTER VARCHAR2(1000 BYTE), 
	RECORD_TABLE VARCHAR2(500 BYTE)
   );
 

   COMMENT ON COLUMN TOS_SYNC_ERROR_LOG.PK_SYNC_ERR_LOG_ID IS 'Auto Generated PK';
 
   COMMENT ON COLUMN TOS_SYNC_ERROR_LOG.PARAMETER_STRING IS 'Parameter String';
 
   COMMENT ON COLUMN TOS_SYNC_ERROR_LOG.PROG_TYPE IS 'Program Type';
 
   COMMENT ON COLUMN TOS_SYNC_ERROR_LOG.OPEARTION_TYPE IS 'Operation Type';
 
   COMMENT ON COLUMN TOS_SYNC_ERROR_LOG.ERROR_MSG IS 'Error Msg';
 
   COMMENT ON COLUMN TOS_SYNC_ERROR_LOG.RERUN_STATUS IS 'Rerun Status';
 
   COMMENT ON COLUMN TOS_SYNC_ERROR_LOG.RECORD_STATUS IS 'Record Status';
 
   COMMENT ON COLUMN TOS_SYNC_ERROR_LOG.RECORD_ADD_USER IS 'Create By';
 
   COMMENT ON COLUMN TOS_SYNC_ERROR_LOG.RECORD_ADD_DATE IS 'Create Date Time';
 
   COMMENT ON COLUMN TOS_SYNC_ERROR_LOG.RECORD_CHANGE_USER IS 'Update By';
 
   COMMENT ON COLUMN TOS_SYNC_ERROR_LOG.RECORD_CHANGE_DATE IS 'Update Date Time';
 
   COMMENT ON TABLE TOS_SYNC_ERROR_LOG  IS 'Sync Error Handler - Sync Error Handler';
 
