 CREATE TABLE TOS_LOG_INFO_DETAIL 
 (PK_LOG_INFO_DETAIL_ID        NUMBER              ,
  FK_LOG_INFO_HEADER_ID NUMBER              , 
  VARIABLE_NAME         VARCHAR2(50 BYTE)   , 
  VARIABLE_VALUE        VARCHAR2(4000 BYTE) , 
  VARIABLE_IO           VARCHAR2(1 BYTE));
 
  ALTER TABLE TOS_LOG_INFO_DETAIL ADD CONSTRAINT PK_LOG_INFO_DETAIL PRIMARY KEY (PK_LOG_INFO_DETAIL_ID);
