@&&ROOT_FOLDER_PATH\VASAPPS\Views\V_TOS_DL_CONTAINER.sql;
@&&ROOT_FOLDER_PATH\VASAPPS\Views\V_TOS_LL_CONTAINER.sql;
@&&ROOT_FOLDER_PATH\VASAPPS\Views\V_TOS_ONBOARD_CONTAINER.sql;
@&&ROOT_FOLDER_PATH\VASAPPS\Views\V_TOS_ONBOARD_LIST.sql;
@&&ROOT_FOLDER_PATH\VASAPPS\Views\V_TOS_DISCHLIST_DTL.sql;