@&&ROOT_FOLDER_PATH\VASAPPS\Data\VCM_CONFIG_MST_DATA.sql;
@&&ROOT_FOLDER_PATH\VASAPPS\Data\ECM_LOOKUP_CONFIG_MST_DATA.sql;
@&&ROOT_FOLDER_PATH\VASAPPS\Data\ZCV_SCREEN_DATA.sql;
@&&ROOT_FOLDER_PATH\VASAPPS\Data\ZCV_SCREEN_COLUMN_DATA.sql;
@&&ROOT_FOLDER_PATH\VASAPPS\Data\ZCV_VIEW_DATA.sql;
@&&ROOT_FOLDER_PATH\VASAPPS\Data\ZCV_VIEW_COLUMN_DATA.sql;
@&&ROOT_FOLDER_PATH\VASAPPS\Data\ZND_E_NOTICE_TYPE_DATA.sql;
@&&ROOT_FOLDER_PATH\VASAPPS\Data\ZND_E_NOTICE_VARIABLE_TYPE_DATA.sql;
@&&ROOT_FOLDER_PATH\VASAPPS\Data\TOS_ERROR_MST_DATA.sql;

